name: sales_filter_application
description: تطبيق فلترة المبيعات.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/logo_company.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/logo_company.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/logo_company.png
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
