/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

/// <reference types="unplugin-vue-router/client" />

import type {
  // type safe route locations
  RouteLocationTypedList,
  RouteLocationResolvedTypedList,
  RouteLocationNormalizedTypedList,
  RouteLocationNormalizedLoadedTypedList,
  RouteLocationAsString,
  RouteLocationAsRelativeTypedList,
  RouteLocationAsPathTypedList,

  // helper types
  // route definitions
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,

  // vue-router extensions
  _RouterTyped,
  RouterLinkTyped,
  RouterLinkPropsTyped,
  NavigationGuard,
  UseLinkFnTyped,

  // data fetching
  _DataLoader,
  _DefineLoaderOptions,
} from 'unplugin-vue-router/types'

declare module 'vue-router/auto/routes' {
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'agents-list': RouteRecordInfo<'agents-list', '/agents-list', Record<never, never>, Record<never, never>>,
    'agents-statistics': RouteRecordInfo<'agents-statistics', '/agents-statistics', Record<never, never>, Record<never, never>>,
    'backup-database': RouteRecordInfo<'backup-database', '/backup-database', Record<never, never>, Record<never, never>>,
    'cash-deposits': RouteRecordInfo<'cash-deposits', '/cash-deposits', Record<never, never>, Record<never, never>>,
    'cash-registers': RouteRecordInfo<'cash-registers', '/cash-registers', Record<never, never>, Record<never, never>>,
    'cash-transfers': RouteRecordInfo<'cash-transfers', '/cash-transfers', Record<never, never>, Record<never, never>>,
    'cash-withdrawals': RouteRecordInfo<'cash-withdrawals', '/cash-withdrawals', Record<never, never>, Record<never, never>>,
    'customers-archived': RouteRecordInfo<'customers-archived', '/customers-archived', Record<never, never>, Record<never, never>>,
    'customers-list': RouteRecordInfo<'customers-list', '/customers-list', Record<never, never>, Record<never, never>>,
    'employees-list': RouteRecordInfo<'employees-list', '/employees-list', Record<never, never>, Record<never, never>>,
    'expense-items': RouteRecordInfo<'expense-items', '/expense-items', Record<never, never>, Record<never, never>>,
    'items-list': RouteRecordInfo<'items-list', '/items-list', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'login-new': RouteRecordInfo<'login-new', '/login-new', Record<never, never>, Record<never, never>>,
    'no-statistics': RouteRecordInfo<'no-statistics', '/no-statistics', Record<never, never>, Record<never, never>>,
    'payments-date-tracking': RouteRecordInfo<'payments-date-tracking', '/payments-date-tracking', Record<never, never>, Record<never, never>>,
    'payments-month': RouteRecordInfo<'payments-month', '/payments-month', Record<never, never>, Record<never, never>>,
    'payments-total': RouteRecordInfo<'payments-total', '/payments-total', Record<never, never>, Record<never, never>>,
    'payments-week': RouteRecordInfo<'payments-week', '/payments-week', Record<never, never>, Record<never, never>>,
    'permission-list': RouteRecordInfo<'permission-list', '/permission-list', Record<never, never>, Record<never, never>>,
    'purchases-list': RouteRecordInfo<'purchases-list', '/purchases-list', Record<never, never>, Record<never, never>>,
    'request-receipt': RouteRecordInfo<'request-receipt', '/request-receipt', Record<never, never>, Record<never, never>>,
    'sales-list': RouteRecordInfo<'sales-list', '/sales-list', Record<never, never>, Record<never, never>>,
    'suppliers-list': RouteRecordInfo<'suppliers-list', '/suppliers-list', Record<never, never>, Record<never, never>>,
    'support': RouteRecordInfo<'support', '/support', Record<never, never>, Record<never, never>>,
    'test': RouteRecordInfo<'test', '/test', Record<never, never>, Record<never, never>>,
    'user-active': RouteRecordInfo<'user-active', '/user-active', Record<never, never>, Record<never, never>>,
    'users-list': RouteRecordInfo<'users-list', '/users-list', Record<never, never>, Record<never, never>>,
    'warehouses-list': RouteRecordInfo<'warehouses-list', '/warehouses-list', Record<never, never>, Record<never, never>>,
  }
}

declare module 'vue-router/auto' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export type RouterTyped = _RouterTyped<RouteNamedMap>

  /**
   * Type safe version of `RouteLocationNormalized` (the type of `to` and `from` in navigation guards).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalized<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationNormalizedLoaded` (the return type of `useRoute()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationNormalizedLoaded<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationResolved` (the returned route of `router.resolve()`).
   * Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationResolved<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationResolvedTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocation` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocation<Name extends keyof RouteNamedMap = keyof RouteNamedMap> = RouteLocationTypedList<RouteNamedMap>[Name]

  /**
   * Type safe version of `RouteLocationRaw` . Allows passing the name of the route to be passed as a generic.
   */
  export type RouteLocationRaw<Name extends keyof RouteNamedMap = keyof RouteNamedMap> =
    | RouteLocationAsString<RouteNamedMap>
    | RouteLocationAsRelativeTypedList<RouteNamedMap>[Name]
    | RouteLocationAsPathTypedList<RouteNamedMap>[Name]

  /**
   * Generate a type safe params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParams<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['params']
  /**
   * Generate a type safe raw params for a route location. Requires the name of the route to be passed as a generic.
   */
  export type RouteParamsRaw<Name extends keyof RouteNamedMap> = RouteNamedMap[Name]['paramsRaw']

  export function useRouter(): RouterTyped
  export function useRoute<Name extends keyof RouteNamedMap = keyof RouteNamedMap>(name?: Name): RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[Name]

  export const useLink: UseLinkFnTyped<RouteNamedMap>

  export function onBeforeRouteLeave(guard: NavigationGuard<RouteNamedMap>): void
  export function onBeforeRouteUpdate(guard: NavigationGuard<RouteNamedMap>): void

  export const RouterLink: RouterLinkTyped<RouteNamedMap>
  export const RouterLinkProps: RouterLinkPropsTyped<RouteNamedMap>

  // Experimental Data Fetching

  export function defineLoader<
    P extends Promise<any>,
    Name extends keyof RouteNamedMap = keyof RouteNamedMap,
    isLazy extends boolean = false,
  >(
    name: Name,
    loader: (route: RouteLocationNormalizedLoaded<Name>) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>
  export function defineLoader<
    P extends Promise<any>,
    isLazy extends boolean = false,
  >(
    loader: (route: RouteLocationNormalizedLoaded) => P,
    options?: _DefineLoaderOptions<isLazy>,
  ): _DataLoader<Awaited<P>, isLazy>

  export {
    _definePage as definePage,
    _HasDataLoaderMeta as HasDataLoaderMeta,
    _setupDataFetchingGuard as setupDataFetchingGuard,
    _stopDataFetchingScope as stopDataFetchingScope,
  } from 'unplugin-vue-router/runtime'
}

declare module 'vue-router' {
  import type { RouteNamedMap } from 'vue-router/auto/routes'

  export interface TypesConfig {
    beforeRouteUpdate: NavigationGuard<RouteNamedMap>
    beforeRouteLeave: NavigationGuard<RouteNamedMap>

    $route: RouteLocationNormalizedLoadedTypedList<RouteNamedMap>[keyof RouteNamedMap]
    $router: _RouterTyped<RouteNamedMap>

    RouterLink: RouterLinkTyped<RouteNamedMap>
  }
}
