# nginx.conf

server {
    listen 80;
    server_name localhost;

    # Proxy لتجاوز CORS عند جلب بيانات المدن من defaultdata API
    location /api-defaultdata/ {
        proxy_pass http://defaultdata.alsaaeidy.com/;
        proxy_set_header Host defaultdata.alsaaeidy.com;
        proxy_set_header Origin "";
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Additional configurations go here...
}
