CREATE TABLE [dbo].[WithdrawalFromBox] (
    [WithdrawalFromBoxID] INT IDENTITY(1,1) NOT NULL,
    [BoxID] INT NULL,
    [Amount] FLOAT NULL,
    [Purpose] NVARCHAR(MAX) NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [UserID] INT NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [CustomerID] INT NULL,
    [EmployeeID] INT NULL,
    [DelegateID] INT NULL,
    [DocumentID] INT NULL,
    [ExchangeItemID] INT NULL,
    [TransferBoxID] INT NULL,
    [BuyID] INT NULL,
    [SupplierID] INT NULL,
    [DelegateSalaryID] INT NULL,
    [EmployeeSalaryID] INT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [BuyBalanceID] INT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_WithdrawalFromBox_BuyBalance] FOREIGN KEY ([BuyBalanceID]) REFERENCES [dbo].[BuyBalance] ([BuyBalanceID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Boxes_BoxID] FOREIGN KEY ([BoxID]) REFERENCES [dbo].[Boxes] ([BoxID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Buys_BuyID] FOREIGN KEY ([BuyID]) REFERENCES [dbo].[Buys] ([BuyID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Customers_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Delegates_DelegateID] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.DelegatesSalaries_DelegateSalaryID] FOREIGN KEY ([DelegateSalaryID]) REFERENCES [dbo].[DelegatesSalaries] ([DelegateSalaryID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Documents_DocumentID] FOREIGN KEY ([DocumentID]) REFERENCES [dbo].[Documents] ([DocumentID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Employees_EmployeeID] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.EmployeesSalaries_EmployeeSalaryID] FOREIGN KEY ([EmployeeSalaryID]) REFERENCES [dbo].[EmployeesSalaries] ([EmployeeSalaryID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.ExchangeItems_ExchangeItemID] FOREIGN KEY ([ExchangeItemID]) REFERENCES [dbo].[ExchangeItems] ([ExchangeItemID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Suppliers_SupplierID] FOREIGN KEY ([SupplierID]) REFERENCES [dbo].[Suppliers] ([SupplierID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.TransferBoxs_TransferBoxID] FOREIGN KEY ([TransferBoxID]) REFERENCES [dbo].[TransferBoxs] ([TransferBoxID]),
    CONSTRAINT [FK_dbo.WithdrawalFromBox_dbo.Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
