CREATE TABLE [dbo].[CustomerBalanceRequest] (
    [CustomerBalanceRequestID] INT IDENTITY(1,1) NOT NULL,
    [DelegateID] INT NULL,
    [CityID] INT NULL,
    [CustomerName] NVARCHAR(255) NULL,
    [Address] NVARCHAR(255) NULL,
    [Longitude] FLOAT NULL,
    [Latitude] FLOAT NULL,
    [CustomerImage] IMAGE NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [PhoneNumber] NVARCHAR(255) NULL,
    [CustomerState] BIT NULL,
    [ShopName] NVARCHAR(255) NULL,
    [StoreAddress] NVARCHAR(255) NULL,
    [NearestFunctionPoint] NVARCHAR(255) NULL,
    [StorePhoneNumber] NVARCHAR(255) NULL,
    [Neighborhood] NVARCHAR(255) NULL,
    [AmountReceverDay] FLOAT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [SelectState] BIT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_CustomerBalanceRequest_Cities] FOREIGN KEY ([CityID]) REFERENCES [dbo].[Cities] ([CityID]),
    CONSTRAINT [FK_CustomerBalanceRequest_Delegates] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID])
);
