CREATE TABLE [dbo].[CustomerSaleBalance] (
    [CustomerSaleBalanceID] INT IDENTITY(1,1) NOT NULL,
    [UserID] INT NULL,
    [CustomerID] INT NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [BoundNumber] INT NULL,
    [DiscountAmountTotal] FLOAT NULL,
    [DiscountAmountTotalDay] FLOAT NULL,
    [AccountZero] BIT NULL,
    [DelegateState] BIT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [StoreBalanceID] INT NULL,
    [DelegateID] INT NULL,
    [DiscountAmountTotalTwoWay] FLOAT NULL,
    [DiscountAmountDayTotalTwoWay] FLOAT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_CustomerSaleBalance_StoreBalance] FOREIGN KEY ([StoreBalanceID]) REFERENCES [dbo].[StoreBalance] ([StoreBalanceID]),
    CONSTRAINT [FK_CustomerSaleBalance_Customers] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]),
    CONSTRAINT [FK_CustomerSaleBalance_Delegates] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_CustomerSaleBalance_Users] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
