CREATE TABLE [dbo].[Customers] (
    [CustomerID] INT IDENTITY(1,1) NOT NULL,
    [DelegateID] INT NULL,
    [UserID] INT NULL,
    [CityID] INT NULL,
    [CustomerName] NVARCHAR(255) NULL,
    [Address] NVARCHAR(255) NULL,
    [Longitude] FLOAT NULL,
    [Latitude] FLOAT NULL,
    [CustomerImage] NVARCHAR(MAX) NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [PhoneNumber] NVARCHAR(255) NULL,
    [CustomerState] BIT NULL,
    [ShopName] NVARCHAR(255) NULL,
    [StoreAddress] NVARCHAR(255) NULL,
    [NearestFunctionPoint] NVARCHAR(255) NULL,
    [StorePhoneNumber] NVARCHAR(255) NULL,
    [Neighborhood] NVARCHAR(255) NULL,
    [AmountReceverDay] FLOAT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [SelectState] BIT NULL DEFAULT ('false'),
    [SaleName] NVARCHAR(255) NULL,
    [ReceiptName] NVARCHAR(255) NULL,
    [IsLegal] BIT NULL DEFAULT ('false'),
    [IsFakeSale] BIT NOT NULL DEFAULT (0),
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_dbo.Customers_dbo.Cities_CityID] FOREIGN KEY ([CityID]) REFERENCES [dbo].[Cities] ([CityID]),
    CONSTRAINT [FK_dbo.Customers_dbo.Delegates_DelegateID] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_dbo.Customers_dbo.Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
