CREATE TABLE [dbo].[CustomerSaleBalanceRequest] (
    [CustomerSaleBalanceRequestID] INT IDENTITY(1,1) NOT NULL,
    [CustomerBalanceRequestID] INT NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [BoundNumber] INT NULL,
    [StoreBalanceID] INT NULL,
    [DelegateID] INT NULL,
    [AccountZero] BIT NULL,
    [DelegateState] BIT NULL,
    [DiscountAmountTotal] FLOAT NULL,
    [DiscountAmountTotalDay] FLOAT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_CustomerSaleBalanceRequest_CustomerBalanceRequest] FOREIGN KEY ([CustomerBalanceRequestID]) REFERENCES [dbo].[CustomerBalanceRequest] ([CustomerBalanceRequestID]),
    CONSTRAINT [FK_CustomerSaleBalanceRequest_StoreBalance] FOREIGN KEY ([StoreBalanceID]) REFERENCES [dbo].[StoreBalance] ([StoreBalanceID]),
    CONSTRAINT [FK_CustomerSaleBalanceRequest_Delegates] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID])
);
