CREATE TABLE [dbo].[CustomersSalesRequest] (
    [CustomerSaleRequestID] INT IDENTITY(1,1) NOT NULL,
    [CustomersRequestID] INT NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [BoundNumber] INT NULL,
    [StoreID] INT NULL,
    [DelegateID] INT NULL,
    [AccountZero] BIT NULL,
    [DelegateState] BIT NULL,
    [DiscountAmountTotal] FLOAT NULL,
    [DiscountAmountTotalDay] FLOAT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_CustomersSalesRequest_CustomersRequest] FOREIGN KEY ([CustomersRequestID]) REFERENCES [dbo].[CustomersRequest] ([CustomersRequestID]),
    CONSTRAINT [FK_dbo.CustomersSalesRequest_dbo.Delegates_DelegateID] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_dbo.CustomersSalesRequest_dbo.Stores_StoreID] FOREIGN KEY ([StoreID]) REFERENCES [dbo].[Stores] ([StoreID])
);
