CREATE TABLE [dbo].[CustomersSales] (
    [CustomerSaleID] INT IDENTITY(1,1) NOT NULL,
    [UserID] INT NULL,
    [CustomerID] INT NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [BoundNumber] INT NULL,
    [StoreID] INT NULL,
    [DelegateID] INT NULL,
    [AccountZero] BIT NULL,
    [DelegateState] BIT NULL,
    [DiscountAmountTotal] FLOAT NULL,
    [DiscountAmountTotalDay] FLOAT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [DiscountAmountTotalTwoWay] FLOAT NULL,
    [DiscountAmountDayTotalTwoWay] FLOAT NULL,
    [MerchantID] INT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_dbo.CustomersSales_dbo.Customers_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]),
    CONSTRAINT [FK_dbo.CustomersSales_dbo.Delegates_DelegateID] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_dbo.CustomersSales_dbo.Stores_StoreID] FOREIGN KEY ([StoreID]) REFERENCES [dbo].[Stores] ([StoreID]),
    CONSTRAINT [FK_dbo.CustomersSales_dbo.Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
