CREATE TABLE [dbo].[AddToBox] (
    [AddToBoxID] INT IDENTITY(1,1) NOT NULL,
    [BoxID] INT NULL,
    [Amount] FLOAT NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [UserID] INT NULL,
    [SupplierID] INT NULL,
    [DelegateID] INT NULL,
    [DateCreate] DATETIME NULL,
    [DateModify] DATETIME NULL,
    [CustomerPaymentID] INT NULL,
    [EmployeeID] INT NULL,
    [DocumentID] INT NULL,
    [CustomerID] INT NULL,
    [TransferBoxID] INT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [CustomerPaymentBalanceID] INT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_AddToBox_CustomerPaymentBalance] FOREIGN KEY ([CustomerPaymentBalanceID]) REFERENCES [dbo].[CustomerPaymentBalance] ([CustomerPaymentBalanceID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Boxes_BoxID] FOREIGN KEY ([BoxID]) REFERENCES [dbo].[Boxes] ([BoxID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Customers_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [dbo].[Customers] ([CustomerID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.CustomersPayments_CustomerPaymentID] FOREIGN KEY ([CustomerPaymentID]) REFERENCES [dbo].[CustomersPayments] ([CustomerPaymentID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Delegates_DelegateID] FOREIGN KEY ([DelegateID]) REFERENCES [dbo].[Delegates] ([DelegateID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Documents_DocumentID] FOREIGN KEY ([DocumentID]) REFERENCES [dbo].[Documents] ([DocumentID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Employees_EmployeeID] FOREIGN KEY ([EmployeeID]) REFERENCES [dbo].[Employees] ([EmployeeID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Suppliers_SupplierID] FOREIGN KEY ([SupplierID]) REFERENCES [dbo].[Suppliers] ([SupplierID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.TransferBoxs_TransferBoxID] FOREIGN KEY ([TransferBoxID]) REFERENCES [dbo].[TransferBoxs] ([TransferBoxID]),
    CONSTRAINT [FK_dbo.AddToBox_dbo.Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
