CREATE TABLE [dbo].[Delegates] (
    [DelegateID] INT IDENTITY(1,1) NOT NULL,
    [UserID] INT NULL,
    [CityID] INT NULL,
    [DelegateName] NVARCHAR(255) NULL,
    [Address] NVARCHAR(255) NULL,
    [PhoneNumber] NVARCHAR(255) NULL,
    [Notes] NVARCHAR(MAX) NULL,
    [DelegateImage] NVARCHAR(MAX) NULL,
    [DelegateState] BIT NULL,
    [ProfitRatio] FLOAT NULL,
    [SelectState] BIT NULL,
    [AsyncState] BIT NULL,
    [AsyncID] NVARCHAR(255) NULL,
    [BoxID] INT NULL,
    [BoxBalanceID] INT NULL,
    [BalanceSaleState] BIT NULL,
    [DeviceSaleState] BIT NULL,
    [BalancePaymentState] BIT NULL,
    [DevicePaymentState] BIT NULL,
    [ReceiptName] NVARCHAR(255) NULL,
    [UpdateReceipt] BIT NULL,
    [DeleteReceipt] BIT NULL,
    [CreatedDate] DATETIME NOT NULL DEFAULT (getdate()),
    [UpdatedDate] DATETIME NULL,
    CONSTRAINT [FK_Delegates_Boxes] FOREIGN KEY ([BoxID]) REFERENCES [dbo].[Boxes] ([BoxID]),
    CONSTRAINT [FK_Delegates_Boxes1] FOREIGN KEY ([BoxBalanceID]) REFERENCES [dbo].[Boxes] ([BoxID]),
    CONSTRAINT [FK_dbo.Delegates_dbo.Cities_CityID] FOREIGN KEY ([CityID]) REFERENCES [dbo].[Cities] ([CityID]),
    CONSTRAINT [FK_dbo.Delegates_dbo.Users_UserID] FOREIGN KEY ([UserID]) REFERENCES [dbo].[Users] ([UserID])
);
