// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'delegate_application';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String LOGOCOMPANY = 'assets/icons/LogoCompany.png';
  static const String LOGOMAIN = 'assets/icons/logoMain.png';
  static const String LOGO_LAST = 'assets/icons/logo_last.png';
  static const String USER = 'assets/icons/user.png';
  static const String BILLING = 'assets/images/billing.png';
  static const String CUSTOMER = 'assets/images/customer.png';
  static const String DATA_TRANSFER = 'assets/images/data-transfer.png';
  static const String SALES = 'assets/images/sales.png';
  static const String STEP1 = 'assets/images/step1.png';
  static const String STEP2 = 'assets/images/step2.png';
  static const String STEP3 = 'assets/images/step3.png';
  static const String STEP4 = 'assets/images/step4.png';
  static const String WELCOMEIMAGE = 'assets/images/welcomeImage.jpg';
}
