ALTER PROCEDURE [dbo].[TrustReceipts_Create]
    @ContractNumber NVARCHAR(100) = NULL,
    @ContractDate DATETIME = NULL,
    @ContractType NVARCHAR(100) = NULL,
    @ContractNotes NVARCHAR(MAX) = NULL,
    @ContractStatus NVARCHAR(100) = NULL,
    @FirstPartyName NVARCHAR(255) = NULL,
    @CompanyType NVARCHAR(100) = NULL,
    @CompanyRepresentativeName NVARCHAR(255) = NULL,
    @CompanyRepresentativeRole NVARCHAR(100) = NULL,
    @BuyerID INT = NULL,
    @BuyerName NVARCHAR(255) = NULL,
    @BuyerNationalCardNumber NVARCHAR(100) = NULL,
    @BuyerGovernorate NVARCHAR(100) = NULL,
    @BuyerWorkOrResidenceAddress NVARCHAR(255) = NULL,
    @BuyerNearestLandmark NVARCHAR(255) = NULL,
    @BuyerPhoneNumber NVARCHAR(50) = NULL,
    @BuyerRationCenterNumber NVARCHAR(100) = NULL,
    @BuyerAffiliation NVARCHAR(150) = NULL,
    @BuyerMukhtarName NVARCHAR(255) = NULL,
    @ProductID INT = NULL,
    @ProductType NVARCHAR(150) = NULL,
    @ProductName NVARCHAR(255) = NULL,
    @ProductDescription NVARCHAR(MAX) = NULL,
    @ProductNumber NVARCHAR(100) = NULL,
    @ProductDeliveryCondition NVARCHAR(150) = NULL,
    @TotalAmountNumber FLOAT = NULL,
    @TotalAmountText NVARCHAR(255) = NULL,
    @FirstInstallmentAmount FLOAT = NULL,
    @FirstInstallmentDate DATETIME = NULL,
    @InstallmentsCount INT = NULL,
    @InstallmentAmount FLOAT = NULL,
    @InstallmentsStartDate DATETIME = NULL,
    @InstallmentsEndDate DATETIME = NULL,
    @RemainingAmount FLOAT = NULL,
    @PaymentMethod NVARCHAR(100) = NULL,
    @ProductDeliveryDate DATETIME = NULL,
    @DeliveryPlace NVARCHAR(255) = NULL,
    @IsProductInspected BIT = 0,
    @InspectionNotes NVARCHAR(MAX) = NULL,
    @IsReceivedByBuyer BIT = 0,
    @TrustReceiptNumber NVARCHAR(100) = NULL,
    @TrustReceiptDate DATETIME = NULL,
    @ReceiptAmountNumber FLOAT = NULL,
    @ReceiptAmountText NVARCHAR(255) = NULL,
    @ReceiverName NVARCHAR(255) = NULL,
    @DelivererName NVARCHAR(255) = NULL,
    @DeliveryReason NVARCHAR(255) = NULL,
    @IdentityDocumentNumber NVARCHAR(100) = NULL,
    @Address NVARCHAR(255) = NULL,
    @PhoneNumber NVARCHAR(50) = NULL,
    @ReceiverSignature NVARCHAR(255) = NULL,
    @DelivererSignature NVARCHAR(255) = NULL,
    @FirstWitnessName NVARCHAR(255) = NULL,
    @FirstWitnessSignature NVARCHAR(255) = NULL,
    @SecondWitnessName NVARCHAR(255) = NULL,
    @SecondWitnessSignature NVARCHAR(255) = NULL,
    @FirstPartySignature NVARCHAR(255) = NULL,
    @SecondPartySignature NVARCHAR(255) = NULL,
    @CashierSignature NVARCHAR(255) = NULL,
    @SalesRepresentativeSignature NVARCHAR(MAX) = NULL,
    @SalesRepresentativeName NVARCHAR(255) = NULL,
    @CashierName NVARCHAR(255) = NULL,
    @DelegateID INT = NULL,
    @CreatedByUserID INT = NULL,
    @IsActive BIT = 1,
    @TrustReceiptID INT OUTPUT
AS
BEGIN
    SET NOCOUNT ON;
    INSERT INTO [dbo].[TrustReceipts] (
        [ContractNumber], [ContractDate], [ContractType], [ContractNotes], [ContractStatus],
        [FirstPartyName], [CompanyType], [CompanyRepresentativeName], [CompanyRepresentativeRole],
        [BuyerID], [BuyerName], [BuyerNationalCardNumber], [BuyerGovernorate], [BuyerWorkOrResidenceAddress],
        [BuyerNearestLandmark], [BuyerPhoneNumber], [BuyerRationCenterNumber], [BuyerAffiliation], [BuyerMukhtarName],
        [ProductID], [ProductType], [ProductName], [ProductDescription], [ProductNumber], [ProductDeliveryCondition],
        [TotalAmountNumber], [TotalAmountText], [FirstInstallmentAmount], [FirstInstallmentDate], [InstallmentsCount],
        [InstallmentAmount], [InstallmentsStartDate], [InstallmentsEndDate], [RemainingAmount], [PaymentMethod],
        [ProductDeliveryDate], [DeliveryPlace], [IsProductInspected], [InspectionNotes], [IsReceivedByBuyer],
        [TrustReceiptNumber], [TrustReceiptDate], [ReceiptAmountNumber], [ReceiptAmountText], [ReceiverName],
        [DelivererName], [DeliveryReason], [IdentityDocumentNumber], [Address], [PhoneNumber],
        [ReceiverSignature], [DelivererSignature], [FirstWitnessName], [FirstWitnessSignature], [SecondWitnessName],
        [SecondWitnessSignature], [FirstPartySignature], [SecondPartySignature], [CashierSignature], [SalesRepresentativeSignature],
        [SalesRepresentativeName], [CashierName], [DelegateID], [CreatedByUserID], [CreatedDate], [IsActive]
    )
    VALUES (
        @ContractNumber, @ContractDate, @ContractType, @ContractNotes, @ContractStatus,
        @FirstPartyName, @CompanyType, @CompanyRepresentativeName, @CompanyRepresentativeRole,
        @BuyerID, @BuyerName, @BuyerNationalCardNumber, @BuyerGovernorate, @BuyerWorkOrResidenceAddress,
        @BuyerNearestLandmark, @BuyerPhoneNumber, @BuyerRationCenterNumber, @BuyerAffiliation, @BuyerMukhtarName,
        @ProductID, @ProductType, @ProductName, @ProductDescription, @ProductNumber, @ProductDeliveryCondition,
        @TotalAmountNumber, @TotalAmountText, @FirstInstallmentAmount, @FirstInstallmentDate, @InstallmentsCount,
        @InstallmentAmount, @InstallmentsStartDate, @InstallmentsEndDate, @RemainingAmount, @PaymentMethod,
        @ProductDeliveryDate, @DeliveryPlace, @IsProductInspected, @InspectionNotes, @IsReceivedByBuyer,
        @TrustReceiptNumber, @TrustReceiptDate, @ReceiptAmountNumber, @ReceiptAmountText, @ReceiverName,
        @DelivererName, @DeliveryReason, @IdentityDocumentNumber, @Address, @PhoneNumber,
        @ReceiverSignature, @DelivererSignature, @FirstWitnessName, @FirstWitnessSignature, @SecondWitnessName,
        @SecondWitnessSignature, @FirstPartySignature, @SecondPartySignature, @CashierSignature, @SalesRepresentativeSignature,
        @SalesRepresentativeName, @CashierName, @DelegateID, @CreatedByUserID, GETDATE(), @IsActive
    );
    
    SET @TrustReceiptID = SCOPE_IDENTITY();
END
