CREATE proc [dbo].[DeleteSelectItemsTransferStoresTemporary]
@SelectItemTransferStoreTemporaryID int = NULL
as
delete from SelectItemsTransferStoresTemporary
where SelectItemTransferStoreTemporaryID=@SelectItemTransferStoreTemporaryID

